name: FlixorTV
options:
  minimumXcodeGenVersion: 2.36.0
packages:
  FlixorKit:
    path: ../../shared/FlixorKit
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: 12.6.0
targets:
  FlixorTV:
    type: application
    platform: tvOS
    deploymentTarget: "16.0"
    sources:
      - path: FlixorTV
    info:
      path: FlixorTV/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flixor.tv
        SWIFT_VERSION: 5.9
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          CODE_SIGNING_ALLOWED: NO
    dependencies:
      - package: FlixorKit
      - package: Nuke
schemes:
  FlixorTV:
    build:
      targets:
        FlixorTV: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
